/*
Print all subsequences of a string.
Given a string, we have to find out all its subsequences of it.A String is a subsequence of a given String,
that is generated by deleting some character of a given string without changing its order.
Input : abc
Output : a, b, c, ab, bc, ac, abc
*/

package Recursion2;
//here we are using Top-down Approach --> in this we are solving the big problem in to the small and till the base Case
public class PrintSubsequences {

    public static void printSequences(String input, String outputSoFar){//Method Overloading
        if (input.length() == 0) {
            System.out.println(outputSoFar);
            return;
        }
        //we choose to not include the first character
        printSequences(input.substring(1), outputSoFar);
        //we choose to include the first character
        printSequences(input.substring(1), outputSoFar + input.charAt(0));
    }

    public static void printSequences(String input){//Method Overloading
        printSequences(input, "");
    }

    public static void main(String[] args) {
        printSequences("xyz");
    }

}
